ECommerce/ECommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('customer/',include('customer.urls')),
    # path('EComAdmin/',include('EComAdmin.urls')),
    # path('seller/',include('seller.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


ECommerce/common/urls.py
from django.urls import path
from . import views

app_name='common'

urlpatterns = [
    path ('cusotmer-signup/', views.c_signup, name='c-signup' ),
    path ('', views.home, name='homepage'),
    path ('customer-login/', views.c_login, name='c-login' ),
    path ('seller-login/', views.s_login, name='s-login' ),
    path ('seller-signup/', views.s_signup, name='s-signup' ),
]

ECommerce/customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path ('homepage/', views.c_home, name='homepage' ),]

ECommerce/EComAdmin/models.py
from django.db import models

# Create your models here.

ECommerce/common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=50)
    email_id = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    password = models.CharField(max_length=50)

    class Meta:
        db_table = 'customer_tb'

class Seller(models.Model):
    s_name = models.CharField(max_length = 50)
    s_account_number = models.BigIntegerField()
    s_company_name = models.CharField(max_length=50)
    s_account_holder_name = models.CharField(max_length=50)
    s_ifsc_code = models.CharField(max_length=50)
    s_branch_name = models.CharField(max_length=50)
    s_email_id = models.CharField(max_length=50)
    s_mobile_number = models.BigIntegerField()
    s_address = models.CharField(max_length=200)
    s_user_name = models.CharField(max_length=50)
    s_password = models.IntegerField()
    s_image = models.ImageField(upload_to='seller/')

    class Meta:
        db_table = 'seller_tb'
    





ECommerce/customer/models.py
from django.db import models

# Create your models here.

ECommerce/seller/models.py
from django.db import models

# Create your models here.

ECommerce/EComAdmin/views.py
from django.shortcuts import render

# Create your views here.

ECommerce/common/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from random import randint
from django.conf import settings

from common.models import Customer, Seller

# Create your views here.

def c_signup(request):
    if request.method=='POST':
        f_name = request.POST['c_fname']
        l_name = request.POST['c_lname']
        e_mail = request.POST['c_email']
        m_number = request.POST['c_mnumber']
        add_ress = request.POST['c_address']
        pass_word = request.POST['c_pass']
        
# these are the fields to update the db details

        customer = Customer(
            first_name = f_name,
            last_name = l_name,
            email_id = e_mail,
            mobile_number = m_number,
            address = add_ress,
            password = pass_word,
        )

        customer.save()

    return render(request, 'common/c_signup.html')

def home(request):
    return render(request, 'common/homepage.html')

def c_login(request):
    msg=''
    if request.method == 'POST' :
        c_username = request.POST['c_username']
        c_password = request.POST['c_password']
        try:
            customer = Customer.objects.get(email_id = c_username,password = c_password)
            request.session['customer']= customer.id
            return redirect('customer:homepage')
        except:
            msg = 'invalid username or password'
    return render(request, 'common/c_login.html', {'message' : msg })

def s_login(request):
    return render(request, 'common/s_login.html')

def s_signup(request):
    msg=''
    if request.method =='POST':
        sname = request.POST['s_fname']
        companyname = request.POST['s_compname']
        accountnum = request.POST['s_bankacc']
        accountholder = request.POST['s_accname']
        ifsc = request.POST['s_ifsc']
        branch = request.POST['s_branch']
        semail = request.POST['s_email']
        s_mobnumber = request.POST['s_mnumber']
        saddress = request.POST['s_address']
        simage = request.FILES['s_image']
        spassword = randint(1111,9999)
        susername = 'sel-' + sname.lower()+str(spassword)

        seller = Seller(

            s_name = sname,
            s_account_number = accountnum,
            s_company_name = companyname,
            s_account_holder_name = accountholder, 
            s_ifsc_code = ifsc,
            s_branch_name = branch,
            s_email_id = semail,
            s_mobile_number = s_mobnumber,
            s_address = saddress,
            s_user_name = susername,
            s_password = spassword,
            s_image = simage,

        )

        seller.save()

        # msg = 'seller registerd successfully'

        # subject = 'login credentials'
        # message = 'Welcome Your Username is' + susername + ' and password is ' + str(spassword)
        # email_from = settings.EMAIL_HOST_USER 

        # send_mail(
        #     subject,
        #     message,
        #     email_from, 
        #     [semail],
        #     fail_silently=False
        # )
    
    return render(request, 'common/s_signup.html',{'message' : msg })

  

ECommerce/customer/views.py
from django.shortcuts import render

from common.models import Customer

# Create your views here.

def c_home(request):
    return render(request, 'customer/homepage.html')

def c_mycart(request):
    return render(request, 'customer/mycart.html')

def c_myorders(request):
    return render(request, 'customer/myorders.html')

def c_changepassword(request):
    return render(request, 'customer/changepassword.html')

ECommerce/seller/views.py
from django.shortcuts import render

# Create your views here.

ECommerce/common/templates/common/c_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
    integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'styles/homepage.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<body>

    <!-- <form>
        <label for="username"><b>User Name:</b></label><br>
        <input type="text" id="user" name="uname" value="Enter Username"><br>
        <label for="password"><b>Password:</b></label><br>
        <input type="text" id="password" name="password" value="Enter your password"> <br>
    </form> -->
    <br>

        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-1 col-form-label"><b>User Name</b></label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" name="c_username">
              </div>
            </div>
            <div class="row mb-3">
              <label for="inputPassword3" class="col-sm-1 col-form-label"><b>Password</b></label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" name="c_password">
              </div>
            </div>

            <button type="submit" class="btn btn-primary">Sign in</button> <br><br>
           <p style="color:brown;"> {{message}}</p>

          </form>


    
</body>
</html>

ECommerce/common/templates/common/c_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        .form{
            padding-left: 0px;
            text-align: center;
        }
        #head {
            padding-left: 0px;
            background-color: violet;
            text-align: center;
        }
    </style>

</head>

<body>

    <div class="form">

        <h2 id="head">Customer Sign up Here</h2>

    

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="fname"> <b>First Name:</b></label><br>
        <input type="text" id="fname" name="c_fname" value="John"><br>
        <label for="lname"><b>Last Name:</b></label><br>
        <input type="text" id="lname" name="c_lname" value="Doe"> <br>
        <label for="email"><b>E Mail:</b></label><br>
        <input type="text" id="email" name="c_email"> <br>
        <label for="mob"><b>Mobile Number:</b></label><br>
        <input type="text" id="mobilenumber" name="c_mnumber" value="9846xxxx"> <br>
        <label for="address"><b>Address:</b></label><br>
        <textarea name="c_address" id="address" cols="30" rows="10"></textarea>
        <br> <br>
        <label for="password"><b>Password:</b></label><br>
        <input type="text" id="password" name="c_pass" value="Abc@123"> <br> <br>

        <!-- <input type="submit" value="SignUp"> -->
        <button type="submit" >SignUp</button>






    </form>

</div>

</body>

</html>

ECommerce/common/templates/common/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles/homepage.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <style>
        #head {
            padding-left: 0px;
            background-color: violet;
            text-align: center;
        }

        #headcaption {
            padding-left: 0px;
            background-color: red;
            text-align: center;
        }

        .button {
            padding-left: 0px;
            text-align: center;
        }
    </style>


</head>

<body>

    <div class="">
        <h1 id="head">Let's Shoppie </h1>
        <h6 id="headcaption">best shopping experience ever</h6>

    </div>

    <div class="button">

<a href="{% url 'common:c-signup' %}" class="btn btn-primary">Customer SignUp</a> <br> <br>
<a href="{% url 'common:c-login' %}" class="btn btn-secondary">Customer Login</a>  <br> <br>
<a href="{% url 'common:s-signup' %}" class="btn btn-info">Seller SignUp</a> <br> <br>
<a href="{% url 'common:s-login' %}" class="btn btn-warning">Seller login</a> <br> <br>
    </div>

</body>

</html>

ECommerce/common/templates/common/s_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
    integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'styles/homepage.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<body>

    <!-- <form>
        <label for="username"><b>User Name:</b></label><br>
        <input type="text" id="user" name="uname" value="Enter Username"><br>
        <label for="password"><b>Password:</b></label><br>
        <input type="text" id="password" name="password" value="Enter your password"> <br>
    </form> -->
    <br>

        <form>
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-1 col-form-label"><b>User Name</b></label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3">
              </div>
            </div>
            <div class="row mb-3">
              <label for="inputPassword3" class="col-sm-1 col-form-label"><b>Password</b></label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3">
              </div>
            </div>

            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>


    
</body>
</html>

ECommerce/common/templates/common/s_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        .form{
            padding-left: 0px;
            text-align: center;
        }
        #head {
            padding-left: 0px;
            background-color: violet;
            text-align: center;
        }
    </style>

</head>

<body>

    <div class="form">

        <h2 id="head">Seller Sign up Here</h2>

    

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="fname"> <b>Full Name:</b></label><br>
        <input type="text" id="fname" name="s_fname" value=""><br>
        <label for="lname"><b>Company Name:</b></label><br>
        <input type="text" id="cname" name="s_compname" value=""> <br>
        <label for="lname"><b>Bank Account No:</b></label><br>
        <input type="number" id="bankacc" name="s_bankacc" value=""> <br>
        <label for="lname"><b>Account Holder Name:</b></label><br>
        <input type="text" id="aname" name="s_accname" value=""> <br>
        <label for="lname"><b>IFSC Code:</b></label><br>
        <input type="text" id="ifsc" name="s_ifsc" value=""> <br>
        <label for="lname"><b>Branch Name:</b></label><br>
        <input type="text" id="branch" name="s_branch" value=""> <br>
        <label for="email"><b>E Mail:</b></label><br>
        <input type="email" id="email" name="s_email"> <br>
        <label for="mob"><b>Mobile Number:</b></label><br>
        <input type="number" id="mobilenumber" name="s_mnumber" value=""> <br>
        <label for="address"><b>Address:</b></label><br>
        <textarea name="s_address" id="address" cols="30" rows="10"></textarea>
        <br> <br>
        <!-- <label for="password"><b>Password:</b></label><br>
        <input type="text" id="password" name="s_pass" value=""> <br> <br> -->

        <label for="lname"><b>Image:</b></label><br>
        <input type="file" id="image" name="s_image" value=""> <br>


        <!-- <input type="submit" value="SignUp"> -->
        <button type="submit" >SignUp</button>
        <br><br>
        <p style="color:brown;"> {{message}}</p>

    </form>

</div>

</body>

</html>

ECommerce/customer/templates/customer/changepassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <style>
        .image {
            border-radius: 2px;
            /* background-color: darkgreen; */
            border: none;
            text-align: center;
            padding: 4px;
            width: 350px;
            height: 400px;
            margin-top: 1px;
            margin-left: 50px;
            float: left;
        }

        .resetform{
            border-radius: 2px;
            /* background-color: darkgreen; */
            border: none;
            text-align: none;
            padding: 4px;
            width: 350px;
            height: 400px;
            margin-top: 50px;
            margin-left: 200px;
            float: left;

        }
    </style>
</head>



<body>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
      </svg>
      
      <div class="alert alert-warning d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          <b>Reset your Password</b>
        </div>
      </div>

    <div class="image">

        <img src="https://img.freepik.com/premium-vector/forgot-password-illustration_65141-418.jpg" alt=""
        height="550">

    </div>

    <div class="resetform">
        <form>
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-1 col-form-label"><b>Old Password</b></label>
              <div class="col-sm-12">
                <input type="username" class="form-control" id="inputEmail3">
              </div>
            </div>
            <div class="row mb-3">
              <label for="inputPassword3" class="col-sm-1 col-form-label"><b>New Password</b></label>
              <div class="col-sm-12">
                <input type="password" class="form-control" id="inputPassword3">
              </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-1 col-form-label"><b>Confirm Password</b></label>
                <div class="col-sm-12">
                  <input type="password" class="form-control" id="inputPassword3">
                </div>
              </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>





</body>

</html>

ECommerce/customer/templates/customer/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<style>
    .navbar {
        background-color: skyblue;
    }

    .tshirt {
        border-radius: 2px;
        /* background-color: darkgreen; */
        border: none;
        text-align: center;
        padding: 4px;
        width: 350px;
        height: 400px;
        margin-top: 100px;
        margin-left: 50px;
        float: left;
    }

    .jeans {
        border-radius: 2px;
        /* background-color: red; */
        border: none;
        text-align: center;
        padding: 4px;
        width: 350px;
        height: 400px;
        margin-top: 100px;
        margin-right: 50px;
        float: right;

    }

    .saree {
        border-radius: 2px;
        /* background-color: red; */
        border: none;
        text-align: center;
        padding: 4px;
        width: 350px;
        height: 400px;
        margin-top: 100px;
        margin-right: 50px;
        margin-left: 470px;

    }
</style>

<body>
    <nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><b>
                    <h3>Let's Shoppie</h3>
                </b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#"><b>Home</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">My Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Logout</b></a>
                    </li>
            </div>
        </div>
    </nav>


    <div class="tshirt">

        <img src="https://www.mydesignation.com/wp-content/uploads/2019/08/malayali-tshirt-mydesignation-mockup-image-latest-golden-.jpg"
            alt="" width="340" height="300">

        <h4>T Shirts</h4>
        <button type="button" class="btn btn-warning">ADD TO CART</button>

    </div>
    <div class="jeans">
        <img src="https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91Pka1f3yKS._UX679_.jpg" alt=""
            width="340" height="300">
            <h4>Jeans</h4>
        <button type="button" class="btn btn-warning">ADD TO CART</button>

    </div>
    <div class="saree">
        <img src="https://assets.ajio.com/medias/sys_master/root/20230120/cTPd/63caaf5faeb269c651ef34c3/-1117Wx1400H-465635879-teal-MODEL.jpg"
            alt="" width="340" height="300">
            <h4>Sarees</h4>
        <button type="button" class="btn btn-warning">ADD TO CART</button>

    </div>





</body>

</html>